from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE
import os
import re

from agents.chart_agent import chart_agent
from utils.content_utils import normalize_report_content
from tools.content_analysis import analyze_report


def _add_chart_slide(prs, title, categories, values, series_name="Value", chart_type="column"):
    chart_slide_layout = prs.slide_layouts[5]
    slide = prs.slides.add_slide(chart_slide_layout)
    slide.shapes.title.text = title

    chart_data = CategoryChartData()
    chart_data.categories = categories
    chart_data.add_series(series_name, values)

    ppt_chart_type = XL_CHART_TYPE.COLUMN_CLUSTERED
    if chart_type == "bar":
        ppt_chart_type = XL_CHART_TYPE.BAR_CLUSTERED

    x, y, cx, cy = Inches(0.5), Inches(1.5), Inches(9), Inches(4.5)
    slide.shapes.add_chart(
        ppt_chart_type,
        x, y, cx, cy,
        chart_data
    )

    return slide


def _add_text_slide(prs, title, lines):
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    tf = slide.placeholders[1].text_frame
    tf.clear()
    for line in lines:
        if not str(line).strip():
            continue
        p = tf.add_paragraph()
        p.text = str(line)
        p.level = 0
        p.font.size = Pt(18)

def generate_ppt(content, topic):
    data = normalize_report_content(content)

    prs = Presentation()

    # ----------------------
    # TITLE SLIDE
    # ----------------------
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)

    slide.shapes.title.text = data["title"]
    subtitle = slide.placeholders[1]
    subtitle.text = f"Generated by Agentic Research Assistant"

    # ----------------------
    # SECTION SLIDES
    # ----------------------
    for section in data["sections"][:8]:

        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)

        # Title
        slide.shapes.title.text = section["heading"]

        # Content (bullets only)
        tf = slide.placeholders[1].text_frame
        tf.clear()

        bullets = section.get("bullets", [])

        if not bullets:
            bullets = [section.get("content", "")[:120]]

        for i, bullet in enumerate(bullets[:5]):
            p = tf.add_paragraph()
            p.text = bullet
            p.level = 0
            p.font.size = Pt(18)

    # ----------------------
    # LLM-PLANNED CHARTS (primary)
    # ----------------------
    chart_insights = []
    llm_charts_added = 0

    try:
        plan = chart_agent(data)
        for chart in plan.get("charts", []):
            categories = chart.get("categories", [])
            values = chart.get("values", [])
            if not categories or not values:
                continue

            _add_chart_slide(
                prs=prs,
                title=chart.get("title", "Chart"),
                categories=categories,
                values=values,
                series_name=chart.get("series_name", "Value"),
                chart_type=chart.get("chart_type", "column"),
            )
            llm_charts_added += 1

            insight = chart.get("insight", "")
            if insight:
                chart_insights.append(f"{chart.get('title', 'Chart')}: {insight}")

    except Exception as e:
        print("LLM chart planning skipped:", e)

    # ----------------------
    # Deterministic fallback charts (if LLM charts unavailable)
    # ----------------------
    if llm_charts_added == 0:
        try:
            analysis = analyze_report(data)
            charts_data = analysis.get("charts_data", {})

            if "top_entities" in charts_data:
                chart_info = charts_data["top_entities"]
                _add_chart_slide(
                    prs=prs,
                    title=chart_info["title"],
                    categories=chart_info["labels"],
                    values=chart_info["values"],
                    series_name="Frequency",
                    chart_type="column",
                )

            if "key_numbers" in charts_data:
                chart_info = charts_data["key_numbers"]
                _add_chart_slide(
                    prs=prs,
                    title=chart_info["title"],
                    categories=chart_info["labels"],
                    values=chart_info["values"],
                    series_name="Values",
                    chart_type="column",
                )

            if "section_focus" in charts_data:
                chart_info = charts_data["section_focus"]
                _add_chart_slide(
                    prs=prs,
                    title=chart_info["title"],
                    categories=chart_info["labels"],
                    values=chart_info["values"],
                    series_name="Entity Mentions",
                    chart_type="bar",
                )

            if "comparisons" in charts_data:
                _add_text_slide(
                    prs=prs,
                    title=charts_data["comparisons"].get("title", "Key Comparisons"),
                    lines=charts_data["comparisons"].get("items", []),
                )

        except Exception as e:
            print("Fallback charts skipped:", e)

    if chart_insights:
        _add_text_slide(prs, "Chart Insights", chart_insights)

    # ----------------------
    # SAVE FILE
    # ----------------------
    safe_topic = re.sub(r"[^a-zA-Z0-9._-]+", "_", topic).strip("_") or "report"
    path = f"outputs/slides/{safe_topic}.pptx"
    os.makedirs(os.path.dirname(path), exist_ok=True)

    prs.save(path)

    return path